"use client";

import { FormEvent, useEffect, useState, type ReactNode } from "react";
import Reveal from "./Reveal";
import { EVENTO, UFS, formatBRL } from "@/lib/event";
import { IcArrow, IcCheck, IcCopy, IcLock, IcCard, IcQr, IcShirt, IcMedal, IcBolt, IcBox } from "./Icons";

type FormData = { nome:string; email:string; telefone:string; cpf:string; nascimento:string; sexo:string; uf:string; tamanho:string; aceiteTermos:boolean; aceiteLgpd:boolean; };
const INIT: FormData = { nome:"", email:"", telefone:"", cpf:"", nascimento:"", sexo:"", uf:"", tamanho:"M", aceiteTermos:false, aceiteLgpd:false };
const STEPS = [{n:"1",label:"Dados pessoais"},{n:"2",label:"Percurso & kit"},{n:"3",label:"Confirmação"}];
const onlyDigits=(s:string)=>s.replace(/\D/g,"");
function maskCpf(v:string){const d=onlyDigits(v).slice(0,11);if(d.length<=3)return d;if(d.length<=6)return `${d.slice(0,3)}.${d.slice(3)}`;if(d.length<=9)return `${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6)}`;return `${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6,9)}-${d.slice(9)}`;}
function maskPhone(v:string){const d=onlyDigits(v).slice(0,11);if(d.length<=2)return d;if(d.length<=7)return `(${d.slice(0,2)}) ${d.slice(2)}`;return `(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`;}
function prettyDate(iso:string){if(!iso)return "—";const [y,m,d]=iso.split("-");return `${d}/${m}/${y}`;}
function Erro({msg}:{msg?:string}){return msg?<p className="mt-1.5 text-[11px] font-600 text-red-400" style={{fontWeight:600}}>{msg}</p>:null;}
function Field({label,children,msg,className=""}:{label:string;children:ReactNode;msg?:string;className?:string}){return <label className={`block ${className}`}><span className="mb-2 block font-data text-[10px] uppercase tracking-[.26em] text-mut">{label}</span>{children}<Erro msg={msg}/></label>;}

export default function InscricaoSection(){
  const [step,setStep]=useState(0); const [form,setForm]=useState<FormData>(INIT); const [errors,setErrors]=useState<Partial<Record<keyof FormData,string>>>({}); const [sending,setSending]=useState(false); const [serverError,setServerError]=useState(""); const [done,setDone]=useState<{code:string}|null>(null); const [copied,setCopied]=useState(false); const [flash,setFlash]=useState(false);
  const set=<K extends keyof FormData>(k:K,v:FormData[K])=>setForm(f=>({...f,[k]:v}));
  useEffect(()=>{const handler=()=>{setFlash(true);setTimeout(()=>setFlash(false),1600);setStep(s=>s===0?1:s);};window.addEventListener("select-prova",handler);return()=>window.removeEventListener("select-prova",handler);},[]);
  const validateData=()=>{const e:Partial<Record<keyof FormData,string>>={};if(form.nome.trim().length<5)e.nome="Informe seu nome completo.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))e.email="E-mail inválido.";if(onlyDigits(form.telefone).length<10)e.telefone="Telefone inválido.";if(onlyDigits(form.cpf).length!==11)e.cpf="CPF deve ter 11 dígitos.";if(!form.nascimento)e.nascimento="Informe sua data de nascimento.";if(!form.sexo)e.sexo="Selecione uma opção.";if(!form.uf)e.uf="Selecione o estado.";setErrors(e);return Object.keys(e).length===0;};
  const next=()=>{if(step===0&&!validateData())return;if(step===1)setErrors({});setStep(s=>Math.min(2,s+1));};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(step<2){next();return;}const validation:Partial<Record<keyof FormData,string>>={};if(!form.aceiteTermos)validation.aceiteTermos="Você precisa aceitar o regulamento.";if(!form.aceiteLgpd)validation.aceiteLgpd="O aceite da política de dados é obrigatório.";setErrors(validation);if(Object.keys(validation).length)return;setSending(true);setServerError("");try{await new Promise(res=>setTimeout(res,700));const code=`INF-${Math.random().toString(36).slice(2,8).toUpperCase()}`;setDone({code});}catch{setServerError("Não foi possível concluir a inscrição. Tente novamente.");}finally{setSending(false);}};
  const copyCode=async()=>{if(!done)return;try{await navigator.clipboard.writeText(done.code);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{/* clipboard indisponível */}};
  const reset=()=>{setForm(INIT);setStep(0);setErrors({});setDone(null);setServerError("");};
  if(done)return <section id="inscricao" className="relative mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-2xl"><Reveal><div className="panel relative overflow-hidden p-8 text-center sm:p-12"><div className="absolute -top-20 left-1/2 h-52 w-52 -translate-x-1/2 rounded-full bg-gold/15 blur-3xl"/><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#006BDF] text-white shadow-[0_16px_40px_-10px_rgba(0,107,223,.8)]"><IcCheck className="h-8 w-8" strokeWidth={2.4}/></span><h2 className="mt-6 font-display text-3xl sm:text-4xl" style={{fontWeight:800}}>Inscrição <span className="gold-grad-text">registrada!</span></h2><p className="mt-3 text-sm leading-relaxed text-mut">Seu lugar na Corrida InforsService foi reservado. Guarde o protocolo abaixo:</p><div className="mx-auto mt-6 flex max-w-md items-center justify-between gap-3 rounded-2xl border border-gold/45 bg-black px-6 py-5"><div className="flex items-center gap-3 text-left"><IcQr className="h-8 w-8 shrink-0 text-gold"/><div><span className="block font-data text-[9px] uppercase tracking-[.3em] text-mut">Protocolo</span><span className="font-data text-xl font-700 tracking-wider text-ivory" style={{fontWeight:700}}>{done.code}</span></div></div><button onClick={copyCode} className="flex items-center gap-2 rounded-xl border border-hair px-4 py-2.5 font-data text-[10px] uppercase tracking-[.2em] text-ivory/80 transition-colors hover:border-gold/60 hover:text-gold"><IcCopy className="h-4 w-4"/>{copied?"Copiado":"Copiar"}</button></div><ul className="mx-auto mt-8 max-w-md space-y-3 text-left">{["Sua inscrição é para o percurso único de 4 km.", `Tamanho de camisa selecionado: ${form.tamanho}.`, "A organização divulgará os próximos passos e informações operacionais pelos canais oficiais.", "Use o protocolo para consultar os dados da sua inscrição."].map((t,i)=><li key={i} className="flex gap-3 text-[13px] leading-relaxed text-ivory/80"><IcCheck className="mt-.5 h-4 w-4 shrink-0 text-gold"/>{t}</li>)}</ul><div className="mt-9 flex flex-wrap items-center justify-center gap-4"><button onClick={reset} className="btn-gold text-sm">Fazer nova inscrição <IcArrow className="h-4 w-4"/></button></div></div></Reveal></div></section>;
  return <section id="inscricao" className="relative border-t border-hair bg-ink2/40"><div className="pointer-events-none absolute left-0 bottom-0 h-96 w-96 rounded-full bg-gold/10 blur-[120px]"/><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-14 lg:grid-cols-[minmax(0,5fr)_minmax(0,7fr)] lg:gap-16">
    <div className="lg:sticky lg:top-28 lg:self-start"><Reveal><div className="flex items-center gap-4"><span className="font-data text-xs tracking-[.4em] text-gold">05</span><span className="h-px flex-1 bg-hair"/><span className="font-data text-[10px] uppercase tracking-[.34em] text-mut">Inscrição</span></div><h2 className="mt-6 font-display text-4xl leading-[1.04] sm:text-5xl" style={{fontWeight:800}}>Garanta a sua<br/><span className="gold-grad-text">linha de chegada.</span></h2><p className="mt-5 max-w-md text-sm leading-relaxed text-mut">Leva poucos minutos. Informe seus dados, escolha o tamanho da camisa e confirme sua inscrição no percurso único de 4 km.</p><div className="mt-8 rounded-2xl border border-gold/40 bg-gold/[.08] p-5"><span className="font-data text-[10px] uppercase tracking-[.3em] text-mut">1º lote · percurso único</span><div className="mt-2 flex items-end justify-between"><span className="font-display text-5xl gold-grad-text" style={{fontWeight:800}}>4 km</span><span className="font-display text-2xl text-ivory" style={{fontWeight:700}}>{formatBRL(EVENTO.precoLote1)}</span></div></div><div className="mt-6 space-y-3"><p className="flex items-center gap-3 text-[12px] text-mut"><IcShirt className="h-4.5 w-4.5 shrink-0 text-gold"/>Camisa, sacola, squeeze e caneta personalizada</p><p className="flex items-center gap-3 text-[12px] text-mut"><IcMedal className="h-4.5 w-4.5 shrink-0 text-gold"/>Medalha com gravação do seu nome no dia</p><p className="flex items-center gap-3 text-[12px] text-mut"><IcLock className="h-4.5 w-4.5 shrink-0 text-gold"/>Dados protegidos conforme a LGPD</p></div></Reveal></div>
    <Reveal delay={120}><form onSubmit={submit} className="panel p-6 sm:p-9"><div className="mb-9 flex items-center gap-2 sm:gap-3">{STEPS.map((s,i)=><div key={s.n} className="flex flex-1 items-center gap-2 sm:gap-3"><button type="button" onClick={()=>i<step&&setStep(i)} className={`flex items-center gap-2.5 ${i<step?"cursor-pointer":"cursor-default"}`} aria-current={i===step?"step":undefined}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl font-data text-sm transition-all duration-300 ${i===step?"bg-[#006BDF] font-700 text-white shadow-[0_8px_20px_-6px_rgba(0,107,223,.75)]":i<step?"border border-gold/60 bg-gold/10 text-gold":"border border-hair text-mut"}`} style={i===step?{fontWeight:700}:undefined}>{i<step?<IcCheck className="h-4 w-4"/>:s.n}</span><span className={`hidden font-data text-[10px] uppercase tracking-[.18em] md:block ${i===step?"text-ivory":"text-mut"}`}>{s.label}</span></button>{i<2&&<span className={`h-px flex-1 transition-colors duration-500 ${i<step?"bg-gold/60":"bg-hair"}`}/>}</div>)}</div>
      {step===0&&<div className="grid gap-5 sm:grid-cols-2"><Field label="Nome completo" msg={errors.nome} className="sm:col-span-2"><input className="field" placeholder="Como está no seu documento" value={form.nome} onChange={e=>set("nome",e.target.value)} autoComplete="name"/></Field><Field label="E-mail" msg={errors.email}><input className="field" type="email" placeholder="voce@email.com" value={form.email} onChange={e=>set("email",e.target.value)} autoComplete="email"/></Field><Field label="Telefone / WhatsApp" msg={errors.telefone}><input className="field" placeholder="(00) 99999-9999" value={form.telefone} onChange={e=>set("telefone",maskPhone(e.target.value))} inputMode="tel" autoComplete="tel"/></Field><Field label="CPF" msg={errors.cpf}><input className="field" placeholder="000.000.000-00" value={form.cpf} onChange={e=>set("cpf",maskCpf(e.target.value))} inputMode="numeric"/></Field><Field label="Data de nascimento" msg={errors.nascimento}><input className="field" type="date" value={form.nascimento} onChange={e=>set("nascimento",e.target.value)}/></Field><Field label="Sexo" msg={errors.sexo}><select className="field" value={form.sexo} onChange={e=>set("sexo",e.target.value)}><option value="">Selecione…</option><option value="Feminino">Feminino</option><option value="Masculino">Masculino</option><option value="Outro / não binário">Outro / não binário</option></select></Field><Field label="Estado (UF)" msg={errors.uf}><select className="field" value={form.uf} onChange={e=>set("uf",e.target.value)}><option value="">Selecione…</option>{UFS.map(u=><option key={u} value={u}>{u}</option>)}</select></Field></div>}
      {step===1&&<div className="space-y-7"><div className={`rounded-2xl border p-6 transition-all duration-500 ${flash?"border-gold bg-gold/[.12]":"border-gold/50 bg-gold/[.07]"}`}><div className="flex items-start justify-between gap-5"><div><span className="font-data text-[10px] uppercase tracking-[.3em] text-gold">Sua corrida</span><h3 className="mt-2 font-display text-4xl text-ivory" style={{fontWeight:800}}>4 KM</h3><p className="mt-2 text-[13px] leading-relaxed text-mut">Percurso único com saída em frente à InforsService.</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#006BDF] text-white"><IcCheck className="h-5 w-5" strokeWidth={2.5}/></span></div><div className="mt-5 flex items-center justify-between border-t border-hair pt-4"><span className="font-data text-[10px] uppercase tracking-[.22em] text-mut">1º lote</span><span className="font-display text-xl gold-grad-text" style={{fontWeight:700}}>{formatBRL(EVENTO.precoLote1)}</span></div></div><div><span className="mb-3 block font-data text-[10px] uppercase tracking-[.26em] text-mut">Tamanho da camisa</span><div className="grid grid-cols-4 gap-2.5">{["P","M","G","GG"].map(t=><button type="button" key={t} onClick={()=>set("tamanho",t)} className={`rounded-xl border px-2 py-3 font-data text-sm transition-all duration-300 ${form.tamanho===t?"border-gold bg-gold/10 font-700 text-ivory":"border-hair bg-black/50 text-mut hover:border-ivory/25"}`} style={form.tamanho===t?{fontWeight:700}:undefined}>{t}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2">{[{icon:IcShirt,t:"Kit do atleta",d:"Camisa, caneta a laser, squeeze a laser e sacola."},{icon:IcMedal,t:"Chegada especial",d:"Medalha com seu nome gravado no dia do evento."},{icon:IcBolt,t:"Antes de correr",d:"Café da manhã e mingau para os atletas."},{icon:IcBox,t:"Pós-corrida",d:"Água, medalhas e troféus para premiados."}].map(x=><div key={x.t} className="flex items-center gap-3 rounded-xl border border-hair bg-black/45 p-4"><x.icon className="h-4.5 w-4.5 shrink-0 text-gold"/><p className="text-[12px] leading-relaxed text-ivory/80"><strong style={{fontWeight:700}}>{x.t}: </strong>{x.d}</p></div>)}</div></div>}
      {step===2&&<div className="space-y-6"><div className="rounded-2xl border border-hair bg-black/60 p-5"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-hair pb-4"><span className="font-data text-[10px] uppercase tracking-[.3em] text-gold">Resumo da inscrição</span><span className="font-data text-[10px] uppercase tracking-[.2em] text-mut">{EVENTO.dataCurta}</span></div><dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3.5 text-[13px] sm:grid-cols-3">{[["Nome",form.nome||"—"],["E-mail",form.email||"—"],["Telefone",form.telefone||"—"],["CPF",form.cpf||"—"],["Nascimento",prettyDate(form.nascimento)],["Sexo / UF",form.sexo?`${form.sexo} · ${form.uf}`:"—"],["Percurso","4 KM"],["Camisa",form.tamanho]].map(([k,v])=><div key={k}><dt className="font-data text-[9px] uppercase tracking-[.26em] text-mut">{k}</dt><dd className="mt-.5 truncate font-600 text-ivory" style={{fontWeight:600}}>{v}</dd></div>)}</dl><div className="mt-4 flex items-center justify-between border-t border-hair pt-4"><span className="font-data text-[10px] uppercase tracking-[.3em] text-mut">1º lote · 4 km</span><span className="font-display text-2xl gold-grad-text" style={{fontWeight:800}}>{formatBRL(EVENTO.precoLote1)}</span></div></div>{[{k:"aceiteTermos" as const,t:"Li e aceito o regulamento da Corrida InforsService e a autorização de uso de imagem do evento."},{k:"aceiteLgpd" as const,t:"Autorizo o tratamento dos meus dados pessoais para fins da inscrição, conforme a LGPD."}].map(c=><label key={c.k} className={`flex cursor-pointer items-start gap-3.5 rounded-2xl border p-4 transition-colors duration-300 ${form[c.k]?"border-gold/50 bg-gold/[.06]":"border-hair bg-black/40 hover:border-ivory/25"}`}><input type="checkbox" className="peer sr-only" checked={form[c.k]} onChange={e=>set(c.k,e.target.checked)}/><span className={`mt-.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition-all duration-300 ${form[c.k]?"border-gold bg-gold text-white":"border-ivory/30 text-transparent"}`}><IcCheck className="h-3.5 w-3.5" strokeWidth={2.6}/></span><span className="text-[13px] leading-relaxed text-ivory/85">{c.t}</span></label>)}<Erro msg={errors.aceiteTermos}/><Erro msg={errors.aceiteLgpd}/>{serverError&&<div className="rounded-2xl border border-red-400/40 bg-red-400/10 p-4 text-[13px] text-red-300">{serverError}</div>}</div>}
      <div className="mt-9 flex items-center justify-between gap-4 border-t border-hair pt-6">{step>0?<button type="button" onClick={()=>setStep(s=>s-1)} className="btn-ghost text-sm">Voltar</button>:<span className="hidden text-[11px] text-mut sm:block">Passo 1 de 3</span>}{step<2?<button type="button" onClick={next} className="btn-gold text-sm">Continuar <IcArrow className="h-4 w-4"/></button>:<button type="submit" disabled={sending} className="btn-gold text-sm">{sending?<><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"/>Enviando…</>:<><IcCheck className="h-4 w-4" strokeWidth={2.4}/>Finalizar inscrição</>}</button>}</div>
    </form></Reveal>
  </div></div></section>;
}
