import Reveal from "./Reveal";
import { IcShirt, IcMedal, IcBox, IcStar, IcBolt, IcCheck, IcClock } from "./Icons";

const KIT = [
  { icon: IcShirt, t: "Camisa da corrida", d: "A sua identidade no percurso" },
  { icon: IcMedal, t: "Medalha com seu nome", d: "Gravação realizada no dia do evento" },
  { icon: IcBolt, t: "Caneta a laser", d: "Gravação personalizada" },
  { icon: IcBolt, t: "Garrafa squeeze", d: "Gravação a laser exclusiva" },
  { icon: IcBox, t: "Sacola", d: "Para levar a experiência com você" },
];
export default function KitSection() { return <section id="kit" className="relative mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid items-center gap-14 lg:grid-cols-2 lg:gap-20">
  <Reveal><div className="relative"><div className="absolute -inset-3 rounded-[26px] border border-gold/35" aria-hidden /><div className="relative overflow-hidden rounded-3xl"><img src="/images/kit.jpg" alt="Itens do kit do atleta" className="h-full w-full object-cover grayscale-[20%] transition-transform duration-[1400ms] ease-out hover:scale-[1.05]" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 rounded-2xl border border-hair bg-black/85 px-6 py-4 backdrop-blur-md"><span className="block font-data text-[10px] uppercase tracking-[0.34em] text-gold">Edição especial</span><span className="mt-1 block font-display text-2xl text-ivory" style={{ fontWeight: 800 }}>SEU NOME<br /><span className="gold-grad-text">NA MEDALHA</span></span><span className="mt-1 block font-data text-[10px] uppercase tracking-[.2em] text-ivory/70">Gravação no dia do evento</span></div></div></div></Reveal>
  <div><Reveal><div className="flex items-center gap-4"><span className="font-data text-xs tracking-[0.4em] text-gold">04</span><span className="h-px flex-1 bg-hair" /><span className="font-data text-[10px] uppercase tracking-[0.34em] text-mut">Kit do atleta</span></div><h2 className="mt-6 font-display text-4xl leading-[1.04] sm:text-5xl" style={{ fontWeight: 800 }}>Seu nome.<br /><span className="gold-grad-text">Sua conquista.</span></h2><p className="mt-5 max-w-lg text-sm leading-relaxed text-mut">Mais do que itens de prova: um kit pensado para guardar esta corrida na memória. A medalha recebe a gravação do seu nome no dia do evento.</p></Reveal>
  <Reveal delay={100}><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3">{KIT.map((it) => <div key={it.t} className="group rounded-2xl border border-hair bg-ink2/70 p-4 transition-all duration-300 hover:-translate-y-1 hover:border-gold/50"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-black text-gold transition-transform duration-300 group-hover:scale-110"><it.icon className="h-4.5 w-4.5" /></span><p className="mt-4 text-[13px] font-700 text-ivory" style={{ fontWeight: 700 }}>{it.t}</p><p className="mt-1 text-[11px] leading-snug text-mut">{it.d}</p></div>)}</div></Reveal>
  <div className="mt-5 grid gap-4 sm:grid-cols-2"><Reveal delay={180}><div className="h-full rounded-2xl border border-gold/35 bg-gold/[.09] p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#006BDF] text-white"><IcClock className="h-4.5 w-4.5" /></span><h3 className="mt-4 font-display text-sm text-ivory" style={{fontWeight:700}}>Antes da corrida</h3><p className="mt-2 text-[12px] leading-relaxed text-ivory/75">Café da manhã e mingau para começar com energia.</p></div></Reveal><Reveal delay={240}><div className="h-full rounded-2xl border border-hair bg-ink2/70 p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-gold/40 bg-black text-gold"><IcMedal className="h-4.5 w-4.5" /></span><h3 className="mt-4 font-display text-sm text-ivory" style={{fontWeight:700}}>Depois da chegada</h3><p className="mt-2 text-[12px] leading-relaxed text-ivory/75">Água, medalha e troféus para os atletas premiados.</p></div></Reveal></div>
  <Reveal delay={300}><ul className="mt-6 space-y-2 text-[12px] text-mut"><li className="flex items-center gap-2.5"><IcCheck className="h-4 w-4 text-gold" />Confira seus dados: eles serão utilizados na personalização da medalha.</li><li className="flex items-center gap-2.5"><IcCheck className="h-4 w-4 text-gold" />As orientações finais de retirada serão divulgadas pela organização.</li></ul></Reveal></div>
</div></section>; }
